config/routes.rb
Synap::Application.routes.draw do
  resources :users 
  resources :datafiles, :path => 'data'
  resources :links_tables, :path => 'link'
  resources :links_users
  resources :relationships
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/recommend', to: 'links_tables#recommendations'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/data', to: 'datafiles#index'
  match '/data/:id/show' => 'datafiles#show'
  match '/data/:id/edit' => 'datafiles#edit'
  match '/data/:id/update', to: 'datafiles#update'

  match '/link/:id', to: 'links_tables#create'
  match '/link', to: 'links_tables#links_table'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/news',    to: 'static_pages#news'
 
  match '/map', to: 'static_pages#about'

end

app/models/data_file.rb
# == Schema Information
#
# Table name: data_files
#
#  id         :integer          not null, primary key
#  Info1      :string(255)
#  Info2      :string(255)
#  Category   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class DataFile < ActiveRecord::Base
  attr_accessible :Category, :Info1, :Info2
  has_many :relationships, foreign_key: "data_file_id", dependent: :destroy
  has_many :users, :through => :relationship

    validates :Info1, presence: true, length: { maximum: 140 }

end

app/models/datafile.rb
# == Schema Information
#
# Table name: datafiles
#
#  id                 :integer          not null, primary key
#  Info1              :string(255)
#  Info2              :string(255)
#  Category           :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  authenticity_token :string(255)
#

class Datafile < ActiveRecord::Base
  attr_accessible :Category, :Info1, :Info2, :user
  has_many :relationships, foreign_key: "datafile_id", dependent: :destroy
  has_many :users, :through => :relationship

    validates :Info1, :uniqueness => { :scope => :Category,
    :message => "Data already contained on file" }, presence: true, length: { maximum: 140 }



  @@return_reason_keys = { "movie" => "movie",
                           "book" => "book",
                           "song" => "song",
                           "other" => "other"}

  def self.return_reason_select
    @@return_reason_keys.invert
  end

  def return_reason
    @@return_reason_keys[Category]
  end

end

app/controllers/data_file_controller.rb
class DataFileController < ApplicationController
  before_filter :signed_in_user

  def index
  	@datafiles = DataFile.paginate(page: params[:page])
  end

  def show
  	@datafile = DataFile.find(params[:id]) 
  end

  def new
  	@datafile = DataFile.new
  end


  def create
    @datafile = DataFile.new(params[:datafiles])
    if @datafile.save
      flash[:success] = "New data added!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  	if @data_file.update_attributes(params[:datafile])
      flash[:success] = "Data updated"
      sign_in @datafile
      redirect_to @datafile
    else
      render 'edit'
    end
  end

  def destroy
    @datafile.destroy
    redirect_to root_url
  end

  private

    def correct_user
      @datafile = current_user.datafile.find_by_id(params[:id])
      redirect_to root_url if @datafile.nil?
    end
end

app/controllers/datafiles_controller.rb
class DatafilesController < ApplicationController
  before_filter :signed_in_user
  before_filter :get_user

  def get_user
    @user = current_user
  end

  def index
  	@datafiles = Datafile.paginate(page: params[:page])
  end

  def show
  	@datafile = Datafile.find(params[:id]) 
      if @datafile.nil?
    @datafiles = Datafile.all
    render "index", :alert => 'Data was not found!'
   end
  end

  def new
  	@datafiles = Datafile.new
  end

  def create
    @datafiles = Datafile.new(params[:datafile])
    if @datafiles.save
      Relationship.create!(:datafile_id => Datafile.last.id, :user_id => current_user.id)
      flash[:success] = "New data added!"
      redirect_to '/data'
    else
      render 'new'
    end
  end

  def edit
    @datafile = Datafile.find(params[:id]) 
  end

  def update
  	if @datafiles.update_attributes(params[:id])
      flash[:success] = "Data updated"
      redirect_to @datafiles
    else
      render 'edit'
    end
  end

  def destroy
    @datafiles.destroy
    redirect_to root_url
  end

  def link
    @title = "Link"
    @datatables = DataTable.find(params[:id])
    render 'show_link'
  end

  def info1
    info = datafile.Info1
    @info1 = link_to "info", datafiles
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/data_file_helper.rb
module DataFileHelper
end

app/helpers/datafiles_helper.rb
module DatafilesHelper

  def current_datafile=(datafile)
    @current_datafile = datafile
  end

  def current_datafile?(datafile)
    datafile == current_datafile
  end

end

app/views/datafiles/_datafile.html.erb
<table class="table table-bordered">
	<thead>
   	 <tr>
		 <th><%= "File Name" %></th>
		 <th><%= "Additional Info:" %></th>
		 <th><%= "Category:" %></th>
		 <th><%= "Link to:" %></th>
     </tr>
    </thead>
     
    <tbody>
	 <% @datafiles.each do |d| %>
	 <tr> 
	    <td> <%= link_to d.Info1, edit_datafile_path(:id => datafile.id) %> </td>
 		<td><%= d.Info2 %></td>
		<td><%= d.Category %></td>
		<th><%  %></th>
	 </tr>
	 <%end%>
	</tbody>

</table>
			<!-- find a way to display category rather then number -->	

app/views/datafiles/datafile.html.erb
<% provide(:title, 'All Data') %>
<h1>All Data</h1>


<h3 class="datafiles">
  <%= render @datafiles %>
</h3>

<% provide(:title, "All data") %>

app/views/datafiles/edit.html.erb
<% provide(:title, "Edit Data") %> 
<h1>Edit the data</h1>

<div class="row">
  <div class="span6 offset3">
      
      <%= form_for(:datafile, url: datafiles_path) do |f| %>

      <%= f.label :Field1 %>
      <%= f.text_field :Info1%>

      <%= f.label :Field2 %>
      <%= f.text_field :Info2%>

      <%= f.label :Category %>
      <%= f.text_field :Category %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>

     <% end %>

  </div>
</div>

<!-- this thing is creating rather then updating, don't know why. must look into it -->

   

app/views/datafiles/index.html.erb
<% provide(:title, 'All data') %>
  <h1>All Data</h1>
  
  <center>
    <h2 class="btn btn-large btn-primary">
      <%= link_to "Add new Data", :controller => "datafiles", :action => "new" %>
    </h2>
  </center>

<%= will_paginate %>

  <ul class="datafiles">
   <%= render @datafiles %> 
  </ul>

 <% provide(:title, "All Data") %>
<%= will_paginate %>

app/views/datafiles/new.html.erb
<% provide(:title, 'New Data') %>
<h1>Add Data</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(:datafile, url: datafiles_path) do |f| %>
      <%= render 'shared/dataerror_messages', object: f.object %>

      <%= f.label :Field1 %>
      <%= f.text_field :Info1 %>

      <%= f.label :Field2 %>
      <%= f.text_field :Info2 %>

      <%= f.label :Category %>
      <%= f.select :Category, options_for_select(Datafile.return_reason_select, @datafiles.Category) %>

      <%= f.submit "Create new data", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/datafiles/show.html.erb
<% provide(:title, :datafile) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
              <%= form_for(:datafile, url: datafiles_path) do |f| %>

      <%= f.label :Field1 %>
      <%= f.text_field :Info1%>

      <%= f.label :Field2 %>
      <%= f.text_field :Info2%>

      <%= f.label :Category %>
      <%= f.text_field :Category %>

     <% end %>
      </h1>
    </section>
  </aside>
  </div>
</div>