config/routes.rb
Synap::Application.routes.draw do
  resources :users 
  resources :datafiles, :path => 'data'
  resources :links_tables, :path => 'link'
  resources :links_users
  resources :relationships
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/recommend', to: 'links_tables#recommendations'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/data', to: 'datafiles#index'
  match '/data/:id/show' => 'datafiles#show'
  match '/data/:id/edit' => 'datafiles#edit'
  match '/data/:id/update', to: 'datafiles#update'

  match '/link/:id', to: 'links_tables#create'
  match '/link', to: 'links_tables#links_table'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/news',    to: 'static_pages#news'
 
  match '/map', to: 'static_pages#about'

end

app/views/shared/_data_file_info.html.erb
<a href="<%= data_file_path(current_datafile) %>">
</a>
<h1>
  <%= current_datafile.info1 %>
</h1>
<span>
  <%= link_to "view my profile", current_datafile %>
</span>
<span>
  <%= pluralize(current_datafile.count, "Data on file") %>
</span>

app/views/shared/_dataerror_messages.html.erb
<!-- error normally relates to the file being entered no the errors function -->
<% if @datafiles.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@datafiles.errors.count, "error") %>.
    </div>
    <ul>
    <% @datafiles.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_datafile_form.html.erb
<%= form_for(@datafile) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new data..." %>
  </div>
      <%= f.text_area :content, placeholder: "Add info..." %>
  </div>
      <% %w{Book Movie Food}.each do |value|-%>
    <% f.radio_button :assistanttype, value %> <% value %><br />
    <% end -%> 
  </div>
  <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
<% end %>

<!-- f.radio_button or f.check_box -->

app/views/shared/_datafile_info.html.erb
<a href="<%= datafile_path(current_datafile) %>">
</a>
<h1>
  <%= current_datafile.info1 %>
</h1>
<span>
  <%= link_to "view my profile", current_datafile %>
</span>
<span>
  <%= pluralize(current_datafile.count, "Data on file") %>
</span>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="datafiles">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">

  <span class="datafile">
    <%= link_to feed_item.datafile.info1, feed_item.datafile %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
</li>

app/views/shared/_linkerror_messages.html.erb
<!-- error normally relates to the file being entered no the errors function -->
<% if @links_tables.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@links_tables.errors.count, "error") %>.
    </div>
    <ul>
    <% @links_tables.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<!-- needs fixing 

<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div> -->

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>