config/routes.rb
Synap::Application.routes.draw do
  resources :users 
  resources :datafiles, :path => 'data'
  resources :links_tables, :path => 'link'
  resources :links_users
  resources :relationships
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/recommend', to: 'links_tables#recommendations'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/data', to: 'datafiles#index'
  match '/data/:id/show' => 'datafiles#show'
  match '/data/:id/edit' => 'datafiles#edit'
  match '/data/:id/update', to: 'datafiles#update'

  match '/link/:id', to: 'links_tables#create'
  match '/link', to: 'links_tables#links_table'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/news',    to: 'static_pages#news'
 
  match '/map', to: 'static_pages#about'

end

app/controllers/links_table_controller.rb
class LinksTableController < ApplicationController
  before_filter :signed_in_user
  before_filter :correct_user,   only: :destroy

  def index
  	@links_tables = LinksTable.paginate(page: params[:page])
  end

  def show
  	@links_table = LinksTable.find(params[:id])
  end

=begin
  def new
  	@links_table = LinksTable.new
  end
=end

def new
  @links_table = LinksTable.new

  # def datafiles #Step 2
  #   @links_table = LinksTable.new
  #   @user = User.find(@links_table.user_id)
  #   @datafiles = Datafile.find(:all)
  #   @links_table.complete = "step1"

  #   respond_to do |format|
  #     if @linking.update_attributes(params[:linking])
  #       flash[:notice] = 'Step one succesful. Item saved.'
  #       format.html #categories.html.erb
  #      end
  #   end
  # end

end


  def create
    @links_table = current_user.links_table.build(params[:links_table])
    if @links_table.save
      flash[:success] = "New file created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'links_table/linksindex'
    end
  end

  def destroy
    @links_table.destroy
    redirect_to root_url
  end

  private

    def correct_user
      @links_table = current_user.links_table.find_by_id(params[:id])
      redirect_to root_url if @links_table.nil?
    end
end

app/controllers/links_tables_controller.rb
class LinksTablesController < ApplicationController
  layout 'linkapplication'

  before_filter :signed_in_user
  before_filter :correct_user,   only: :destroy


  def recommendations
  end

  def index
  	@links_tables = LinksTable.paginate(page: params[:page])
  end

  def show
  	@links_table = LinksTable.find(params[:id])
  end

  def new
    @links_table = LinksTable.new
  end

  def create
    @links_table = LinksTable.new(params[:links_table])
    if @links_table.save
      LinksUser.create!(:links_table_id => LinksTable.last.id, :user_id => current_user.id)
      flash[:success] = "Data Linked!"
      redirect_to :back, :alert => 'Linked!'
    else
      render "new", :alert => 'Link not made!'
    end
  end

  def destroy
    @links_table.destroy
    redirect_to root_url
  end

  def Recommendations
  end 

  private

    def correct_user
      @links_table = current_user.links_table.find_by_id(params[:id])
      redirect_to root_url if @links_table.nil?
    end
end

app/helpers/links_table_helper.rb
module LinksTableHelper
end

app/views/links_tables/_links_table.html.erb
<div>
	<%= link_to links_table.link1, links_table %>
	<%= "makes me think of..." %> <%= link_to links_table.link2, links_table %> <br>
<div>

app/views/links_tables/_new.html.erb
<div class="row">
  <div class="span6 offset3">

    <%= form_for(:links_table, url: links_tables_path) do |f| %>

      <%= f.label :Link %>
      <%= f.collection_select :link1, Datafile.find(:all), :id, :Info1, :prompt => true  %>

      <%= f.label :to %>
      <%= f.collection_select :link2, Datafile.find(:all), :id, :Info1, :prompt => true  %>

      <%= f.submit "Create link", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/links_tables/index.html.erb
<% provide(:title, 'All Links') %>
  <h1>All Links</h1>
  
  <center>
    <h2 class="btn btn-large btn-primary">
      <%= link_to "Add new link", :controller => "links_tables", :action => "new"%>
    </h2>
  </center>



<ul class="links_tables">
  <%= render @links_tables %> 
</ul>

 <% provide(:title, "All") %>

app/views/links_tables/links_table.html.erb
<% provide(:title, 'All Links') %>
<h1>All Links</h1>

<ul class="links_tables">
  <%= render @links_tables %> 
</ul>

<% provide(:title, "All Links") %>

app/views/links_tables/new.html.erb
<% provide(:title, 'Add Links') %>
<h2>Add Links</h2>

<div class="row">
  <div class="span6 offset3">

    <%= form_for(:links_table, url: links_tables_path) do |f| %>
< "render 'shared/linkerror_messages', object: f.object" >

      <%= f.label :Link %>
      <%= f.collection_select :link1, Datafile.find(:all), :id, :Info1, :prompt => true  %>

      <%= f.label :to %>
      <%= f.collection_select :link2, Datafile.find(:all), :id, :Info1, :prompt => true  %>

      <%= f.submit "Create link", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/links_tables/recommendations.html.erb
<% provide(:title, "Recommendations") %>
<div class="row">
  <aside class="span4">
    <section>
      <body>
      
   <%= "You linked to " %><%= "Zaynub" %> <%= ". Based on that I think you would like " %> <%= "Farnaz" %> 
       <br>
     </body>
    </section>
  </aside>
  
  </div>


<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%=  %>
      </h1>
    </section>
    
    <section>
      <%= "render 'users/new'" %>
    </section>
  
  </aside>
  <div class="span8">
    <%= "render 'users/new1'"%>
    <%  %>

  </div>
</div>