config/routes.rb
Synap::Application.routes.draw do
  resources :users 
  resources :datafiles, :path => 'data'
  resources :links_tables, :path => 'link'
  resources :links_users
  resources :relationships
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/recommend', to: 'links_tables#recommendations'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/data', to: 'datafiles#index'
  match '/data/:id/show' => 'datafiles#show'
  match '/data/:id/edit' => 'datafiles#edit'
  match '/data/:id/update', to: 'datafiles#update'

  match '/link/:id', to: 'links_tables#create'
  match '/link', to: 'links_tables#links_table'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/news',    to: 'static_pages#news'
 
  match '/map', to: 'static_pages#about'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <link>
    <%= render 'links_tables/new' %>
  </link>
   
 <br>
  <hr>
 <br>
  
  <small>
    <a href="http://www.Synaps.org/">A new way to arrange your thoughts</a>
    by Zahara Khan
  </small>
  
  <nav>
    <div>
     <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "News", news_path %></li>
      <li><%= link_to "Help", help_path %></li>
     </ul>
    </div>
  </nav>

</br>

</footer>

app/views/layouts/_header.html.erb
<header>
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Synap", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Data", data_path %></li>

           <% if signed_in? %>
            <li><%= link_to "My Links", link_path %></li>
            <li><%= link_to "My Map", map_path %></li>
            <li><%= link_to "Recommend", recommend_path %></li>
            
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Edit Data", data_path %></li>

                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_linkfooter.html.erb
<footer class="footer">

  <hr>
  
  <small>
    <a href="http://www.Synaps.org/">A new way to arrange your thoughts</a>
    by Zahara Khan
  </small>
  
  <nav>
    <div>
     <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "News", news_path %></li>
      <li><%= link_to "Help", help_path %></li>
     </ul>
    </div>
  </nav>

</footer>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/linkapplication.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/linkfooter' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>``